require_relative 'ruby_anagrams/subtrees'
require_relative 'ruby_anagrams/enumerable'
require_relative 'ruby_anagrams/anagrams'
require_relative 'ruby_anagrams/node'
require_relative 'ruby_anagrams/root'